-- ==========================================
-- 1. INFRASTRUCTURE & ENVIRONMENT
-- ==========================================
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE RELIEF_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE NGO_INVENTORY_DB;
CREATE OR REPLACE SCHEMA NGO_INVENTORY_DB.LOGISTICS;

USE DATABASE NGO_INVENTORY_DB;
USE SCHEMA LOGISTICS;
USE WAREHOUSE RELIEF_WH;

-- ==========================================
-- 2. BASE DATA STRUCTURES (THE SILOS)
-- ==========================================

-- Current Physical Inventory
CREATE OR REPLACE TABLE CURRENT_STOCK (
    LOCATION_ID STRING,
    ITEM_NAME STRING,
    STOCK_ON_HAND INT,
    CRITICALITY_SCORE INT, 
    LAST_UPDATED TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Consumption/Demand History
CREATE OR REPLACE TABLE USAGE_HISTORY (
    LOCATION_ID STRING,
    ITEM_NAME STRING,
    UNITS_USED_DAILY INT, 
    REPORT_DATE DATE DEFAULT CURRENT_DATE()
);

-- Procurement pipeline (Incoming supplies)
CREATE OR REPLACE TABLE PENDING_ORDERS (
    ORDER_ID STRING,
    ITEM_NAME STRING,
    LOCATION_ID STRING,
    QTY_EXPECTED INT,
    LEAD_TIME_DAYS INT 
);

-- NEW: ACTION LAYER (Satisfies Unistore/Log requirement)
CREATE OR REPLACE TABLE PROCUREMENT_ACTIONS (
    ACTION_ID INT IDENTITY(1,1),
    ITEM_NAME STRING,
    LOCATION_ID STRING,
    ACTION_TAKEN STRING,
    ACTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ==========================================
-- 3. SEED DATA (POPULATING THE SCENARIOS)
-- ==========================================

INSERT INTO CURRENT_STOCK (LOCATION_ID, ITEM_NAME, STOCK_ON_HAND, CRITICALITY_SCORE) VALUES 
('LOC-ALPHA', 'Paracetamol', 1000, 8), 
('LOC-BETA', 'Paracetamol', 45, 8),      
('LOC-ALPHA', 'Oxygen Cylinders', 45, 10),
('LOC-BETA', 'Oxygen Cylinders', 8, 10),   
('LOC-ALPHA', 'Amoxicillin', 500, 9),
('LOC-BETA', 'Amoxicillin', 12, 9);       

INSERT INTO USAGE_HISTORY (LOCATION_ID, ITEM_NAME, UNITS_USED_DAILY) VALUES 
('LOC-ALPHA', 'Paracetamol', 50), 
('LOC-BETA', 'Paracetamol', 25),  
('LOC-ALPHA', 'Oxygen Cylinders', 10),
('LOC-BETA', 'Oxygen Cylinders', 4), 
('LOC-ALPHA', 'Amoxicillin', 30),
('LOC-BETA', 'Amoxicillin', 6);

INSERT INTO PENDING_ORDERS VALUES 
('PO-701', 'Paracetamol', 'LOC-BETA', 500, 5),     
('PO-702', 'Oxygen Cylinders', 'LOC-ALPHA', 50, 2),
('PO-703', 'Amoxicillin', 'LOC-BETA', 100, 4);

-- ==========================================
-- 4. THE ANALYTICS ENGINE (DYNAMIC TABLE)
-- ==========================================
CREATE OR REPLACE DYNAMIC TABLE STOCK_HEALTH_ANALYTICS
TARGET_LAG = '1 minute'
WAREHOUSE = RELIEF_WH
AS
SELECT 
    s.LOCATION_ID,
    s.ITEM_NAME,
    s.STOCK_ON_HAND,
    s.CRITICALITY_SCORE,
    u.UNITS_USED_DAILY as DAILY_BURN_RATE,
    (s.STOCK_ON_HAND / NULLIF(u.UNITS_USED_DAILY, 0)) as DAYS_UNTIL_OUT,
    p.LEAD_TIME_DAYS as ARRIVAL_TIME,
    ((s.STOCK_ON_HAND / NULLIF(u.UNITS_USED_DAILY, 0)) - p.LEAD_TIME_DAYS) as SAFETY_BUFFER
FROM CURRENT_STOCK s
LEFT JOIN USAGE_HISTORY u ON s.LOCATION_ID = u.LOCATION_ID AND s.ITEM_NAME = u.ITEM_NAME
LEFT JOIN PENDING_ORDERS p ON s.LOCATION_ID = p.LOCATION_ID AND s.ITEM_NAME = p.ITEM_NAME;

-- This table logs when a human approves an emergency reorder
CREATE OR REPLACE TABLE NGO_INVENTORY_DB.LOGISTICS.PROCUREMENT_ACTIONS (
    ACTION_ID INT IDENTITY(1,1),
    ITEM_NAME STRING,
    LOCATION_ID STRING,
    ACTION_TAKEN STRING,
    ACTION_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SHOW FUNCTIONS LIKE '%COMPLETE%' IN SNOWFLAKE.CORTEX;

-- This lists the models currently available to your account's region
SELECT * FROM TABLE(INFORMATION_SCHEMA.CORTEX_MODELS());

SHOW FUNCTIONS IN SERVICE SNOWFLAKE.CORTEX;


CREATE TABLE IF NOT EXISTS NGO_INVENTORY_DB.LOGISTICS.PROCUREMENT_ACTIONS (
    ITEM_NAME VARCHAR,
    LOCATION_ID VARCHAR,
    ACTION_TAKEN VARCHAR,
    ACTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

GRANT USAGE, OPERATE ON WAREHOUSE RELIEF_WH TO ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

SHOW DYNAMIC TABLES;
-- If 'state' is not 'STARTED', run:
ALTER DYNAMIC TABLE NGO_INVENTORY_DB.LOGISTICS.STOCK_HEALTH_ANALYTICS RESUME;

